name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-api-sch.vercel.app/"
        with:
          build: npm run build
          start: npm start
